name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: bookstore_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install

      - name: Copy .env.testing
        run: cp .env.example .env.testing

      - name: Start Docker Compose services
        run: docker-compose -f path/to/your/docker-compose.yml up -d

      - name: Wait for PostgreSQL to be ready
        run: docker-compose -f path/to/your/docker-compose.yml exec -T db pg_isready --wait

      - name: Run migrations
        run: docker-compose -f path/to/your/docker-compose.yml exec -T app php artisan migrate --env=testing

      - name: Run tests
        run: docker-compose -f path/to/your/docker-compose.yml exec -T app php artisan test
